import { AlertTriangle, CheckCircle2, Cloud, Database, Gauge, Globe2 } from "lucide-react";
import { AppShell } from "@/components/shell";
import { Badge, MetricCard, Progress, SectionHeading } from "@/components/ui";
import { IntegrationStatusPanel } from "@/components/integrations/IntegrationStatusPanel";
import { LiveDataPanel } from "@/components/integrations/LiveDataPanel";

export default function BetaPage() {
  return <AppShell title="Beta Readiness Center" eyebrow="Public beta control plane">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-cyan">Release candidate</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Operationally honest. Deployment ready.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-mist">A transparent view of deployment posture, public data coverage, fallbacks, and the integrations still required before a live airport pilot.</p></div><Badge tone="amber">Beta data mode</Badge></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Beta readiness" value="88/100" detail="code and experience" icon={Gauge}/><MetricCard label="Vercel target" value="Ready" detail="production settings required" icon={Cloud}/><MetricCard label="Static demo" value="Ready" detail="GitHub Pages pathway" icon={Globe2}/><MetricCard label="Data resilience" value="5 layers" detail="fallback protected" icon={Database}/></div>
    <div className="mt-7 grid gap-7 xl:grid-cols-[1.1fr_.9fr]"><section className="glass p-6"><SectionHeading eyebrow="Deployment status" title="Release gates"/><div className="space-y-4">{[["Root build and package manifest",100],["Vercel production configuration",90],["GitHub Pages static export",100],["Free API fallback coverage",95],["Enterprise security and governance",42]].map(([label,value])=><div key={String(label)}><div className="mb-2 flex justify-between text-xs"><span>{label}</span><b>{value}%</b></div><Progress value={Number(value)} tone={Number(value)>80?"emerald":"amber"}/></div>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-4"><CheckCircle2 className="text-emerald-300"/><b className="mt-3 block text-sm">Vercel production</b><p className="mt-1 text-[11px] text-mist">Code target ready. Domain and Git branch linkage are controlled in Vercel.</p></div><div className="rounded-2xl border border-cyan/20 bg-cyan/10 p-4"><Globe2 className="text-cyan"/><b className="mt-3 block text-sm">GitHub Pages demo</b><p className="mt-1 text-[11px] text-mist">Static feature demo only; Vercel remains the primary platform.</p></div></div></section><LiveDataPanel/></div>
    <section className="glass mt-7 p-6"><SectionHeading eyebrow="API integration status" title="Beta-safe service boundary"/><IntegrationStatusPanel/></section>
    <section className="glass mt-7 p-6"><SectionHeading eyebrow="Known limitations" title="What this beta does not claim"/><div className="grid gap-3 md:grid-cols-3">{["Operational metrics are simulated and must not drive real-world security decisions.","Public APIs can be rate-limited or incomplete; fallback mode is deliberately visible.","Production requires privacy, cybersecurity, airline, airport, regulator, and hardware validation."].map((text)=><div key={text} className="rounded-2xl border border-amber-400/20 bg-amber-400/[.06] p-4"><AlertTriangle size={17} className="text-amber-300"/><p className="mt-3 text-xs leading-5 text-mist">{text}</p></div>)}</div></section>
  </AppShell>;
}
