"use client";
import { useMemo, useState } from "react";
import { CheckCircle2, Link2, ScanLine, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/shell";
import { DigitalTagSimulator } from "@/components/tagging/DigitalTagSimulator";
import { bindBagIdentity } from "@/lib/tagging/tagBindingEngine";

export default function TaggingPage(){
 const [issued,setIssued]=useState(false); const [name,setName]=useState("Omoluabi Paul"); const [flight,setFlight]=useState("BA 074"); const [origin,setOrigin]=useState("LOS"); const [destination,setDestination]=useState("LHR");
 const result=useMemo(()=>bindBagIdentity({passenger:{id:"PAX-0001",name,passportRef:"PP-••7400",boardingPassRef:"BP-BA074-12A"},flight:{flightNumber:flight,origin,destination,departure:"2026-06-15T09:30:00Z"},physicalProfile:{weightKg:18.4,dimensionsCm:[68,45,27],color:"Navy",sizeClass:"Medium",shellType:"Soft shell",handleType:"Dual rail",wheelType:"Four spinner",scratches:[],stickers:["Green travel sticker"],dents:[],markings:["Blue handle tape"],brandIndicators:["Front badge"]}}),[name,flight,origin,destination]);
 return <AppShell title="Tag Issuance Station" eyebrow="Check-in protocol · Issue and bind"><div className="grid gap-6 2xl:grid-cols-[1.15fr_.85fr]"><section className="glass p-6"><div className="mb-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-gold">Station LOS-C12</p><h2 className="mt-2 text-2xl font-semibold">Create a digital baggage identity</h2><p className="mt-2 text-xs leading-5 text-mist">Bind the passenger reference, itinerary, physical bag, secure tag, RFID, NFC, rotating QR, seal, and visual fingerprint in one issuance event.</p></div><div className="grid gap-4 sm:grid-cols-2">{[["Passenger name",name,setName],["Passport reference","PP-••7400",()=>{}],["Boarding pass reference","BP-BA074-12A",()=>{}],["Flight",flight,setFlight],["Origin airport",origin,setOrigin],["Destination airport",destination,setDestination],["Bag weight","18.4 kg",()=>{}],["Dimensions","68 × 45 × 27 cm",()=>{}]].map(([label,value,setter])=><label key={label as string} className="text-[10px] text-mist">{label as string}<input value={value as string} onChange={(e)=>(setter as (x:string)=>void)(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b2134] p-3 text-sm text-white"/></label>)}</div><div className="mt-4 rounded-2xl border border-dashed border-cyan/30 bg-cyan/[.04] p-5 text-center"><ScanLine className="mx-auto text-cyan"/><b className="mt-2 block text-sm">Bag image captured</b><p className="mt-1 text-[10px] text-mist">Navy · medium · soft shell · four spinner wheels · green sticker</p></div><button onClick={()=>setIssued(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-gold p-4 text-xs font-black text-ink"><Link2 size={16}/> Generate, encode and bind tag</button></section><div className="space-y-6"><DigitalTagSimulator flight={flight} origin={origin} destination={destination} bagDnaId={issued?result.bagDnaId:"BD-PENDING"}/>{issued&&<section className="glass p-5"><div className="flex items-center gap-3 text-emerald-300"><CheckCircle2/><div><b className="text-sm">Issued and Bound</b><p className="text-[10px] text-mist">All identity layers committed to custody event.</p></div></div><div className="mt-4 space-y-2 font-mono text-[10px]">{[["BAG-DNA ID",result.bagDnaId],["Encrypted token",result.encryptedToken],["RFID UID",result.rfidUid],["NFC UID",result.nfcUid],["Tamper seal",result.tamperSealId],["Visual fingerprint",result.visualFingerprintId]].map(([a,b])=><p key={a} className="flex justify-between gap-4 border-t border-white/[.06] pt-2"><span className="text-mist">{a}</span><span className="truncate text-cyan">{b}</span></p>)}</div><p className="mt-4 flex items-center gap-2 text-[10px] text-mist"><ShieldCheck size={13} className="text-emerald-300"/> Visible tag exposes flight and route only; passenger details remain encrypted.</p></section>}</div></div></AppShell>
}

