import Link from "next/link";
import { ArrowRight, Building2, Globe2, Lightbulb, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/logo";

export default function AboutPage() {
  return <main className="grid-field min-h-screen bg-ink">
    <header className="border-b border-white/[.07]"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6"><Logo/><Link href="/dashboard" className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-gold">Enter platform <ArrowRight size={13}/></Link></div></header>
    <section className="relative overflow-hidden py-28"><div className="absolute right-[-10%] top-[-30%] h-[600px] w-[600px] rounded-full border border-cyan/10"/><div className="mx-auto max-w-7xl px-6"><div className="max-w-4xl"><p className="text-[10px] font-bold uppercase tracking-[.28em] text-gold">ETL GIS Consulting LLC</p><h1 className="mt-6 font-display text-5xl font-semibold leading-[1.08] md:text-7xl">Geospatial intelligence<br/>for a <span className="text-cyan">safer world.</span></h1><p className="mt-8 max-w-2xl text-base leading-8 text-mist">We build mission-grade geospatial and aviation intelligence systems that transform complex operational data into clear, confident decisions.</p></div></div></section>
    <section className="border-y border-white/[.07] bg-[#091b2a] py-20"><div className="mx-auto grid max-w-7xl gap-px bg-white/[.07] px-6 md:grid-cols-3">{[
      [Globe2,"Geospatial by design","Location is the connective tissue of operations. We engineer every system with spatial context at its core."],
      [ShieldCheck,"Security minded","Our products prioritize traceability, controlled access and defensible operational intelligence."],
      [Lightbulb,"Built for adoption","Advanced capability only matters when people can use it. We make complexity clear and actionable."]
    ].map(([Icon,title,text])=>{const C=Icon as typeof Globe2;return <div key={title as string} className="bg-[#0b2134] p-8"><C className="text-gold" size={22}/><h2 className="mt-7 font-display text-xl">{title as string}</h2><p className="mt-3 text-xs leading-6 text-mist">{text as string}</p></div>})}</div></section>
    <section className="py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2"><div><div className="flex items-center gap-3 text-gold"><Building2 size={17}/><p className="text-[10px] font-bold uppercase tracking-[.24em]">Our mission</p></div><h2 className="mt-6 font-display text-4xl">Make critical movement visible, accountable and resilient.</h2></div><div><p className="text-sm leading-7 text-mist">BAG-DNA OS represents our belief that aviation baggage deserves the same intelligence, identity and security rigor applied to other critical infrastructure. We are creating a shared operational truth for airports, airlines, ground handlers, security agencies and passengers.</p><p className="mt-5 text-sm leading-7 text-mist">ETL GIS Consulting LLC is a U.S.-based technology consultancy focused on GIS, data engineering, digital twins and intelligent operations.</p><Link href="/dashboard" className="mt-8 inline-flex items-center gap-3 bg-gold px-6 py-4 text-[10px] font-bold uppercase tracking-widest text-ink">Experience BAG-DNA OS <ArrowRight size={13}/></Link></div></div></section>
    <footer className="border-t border-white/[.07] py-8"><div className="mx-auto flex max-w-7xl justify-between px-6 text-[9px] uppercase tracking-widest text-mist"><span>ETL GIS Consulting LLC</span><span>United States · Built for global aviation</span></div></footer>
  </main>
}
