"use client";

import { motion } from "framer-motion";
import dynamic from "next/dynamic";
import Link from "next/link";
import { ArrowRight, Check, ChevronRight, FileCheck2, Fingerprint, Globe2, Map, Menu, Network, Radar, ShieldCheck, X } from "lucide-react";
import { useState } from "react";
import { Logo } from "@/components/logo";

const ThreeScene = dynamic(() => import("@/components/ThreeScene"), { ssr: false });

const reveal = {
  initial: { opacity: 0, y: 22 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, amount: 0.2 },
  transition: { duration: 0.65 },
};

const capabilities = [
  { icon: Fingerprint, title: "Persistent bag identity", text: "Bind every checked bag to its passenger, journey, physical attributes, and secure credentials.", href: "/registry" },
  { icon: Network, title: "Verified chain of custody", text: "Turn every handoff into a timestamped, explainable, and defensible evidence event.", href: "/custody" },
  { icon: Radar, title: "AI risk intelligence", text: "Surface identity mismatches, route deviations, and custody breaks before escalation.", href: "/risk" },
  { icon: Map, title: "Global operational twin", text: "See baggage movement, facilities, controls, and risk in one geospatial command layer.", href: "/digital-twin" },
];

const alignment = [
  { title: "Security-control mapping", value: "91%", text: "Identity assurance, screening evidence, custody integrity, anomaly escalation, and controlled intervention." },
  { title: "Facilitation mapping", value: "86%", text: "Interoperable processing, passenger protection, operational continuity, and accountable information exchange." },
  { title: "Governance evidence", value: "93%", text: "Privacy, cybersecurity, human oversight, auditability, and verifiable evidence export." },
];

const journey = [
  ["01", "Issue identity", "Create a persistent BAG-DNA identity for the passenger, journey, and physical bag."],
  ["02", "Bind every layer", "Link secure tag, RFID, NFC, rotating QR, tamper seal, weight, and visual fingerprint."],
  ["03", "Verify every scan", "Reconcile identity, route, custody stage, staff assignment, seal, weight, and appearance."],
  ["04", "Detect and preserve", "Stop mismatches, preserve evidence, and release the bag only after trusted claim verification."],
];

function ProductPreview() {
  return <motion.div initial={{ opacity: 0, y: 34, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: 0.9, delay: 0.2 }} className="hero-console relative mx-auto max-w-6xl">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[.08] px-5 py-4 md:px-7">
      <div className="flex items-center gap-3"><span className="flex gap-1.5"><i/><i/><i/></span><span className="text-[11px] font-semibold text-white/70">International Corridor · Live Demonstration</span></div>
      <div className="flex flex-wrap gap-2"><span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1 text-[10px] font-semibold text-emerald-300">All systems nominal</span><span className="rounded-full border border-gold/30 bg-gold/10 px-3 py-1 text-[10px] font-semibold text-gold">ICAO alignment review</span></div>
    </div>
    <div className="grid gap-4 p-4 md:grid-cols-12 md:p-6">
      <div className="grid gap-4 sm:grid-cols-3 md:col-span-12">{[["12,847","Active bags","Multi-airport network"],["99.84%","Custody verification","Evidence continuity"],["91%","Security mapping","Review package prepared"]].map(([value,label,detail])=><div className="console-card p-5" key={label}><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-slate-400">{label}</p><p className="mt-4 text-3xl font-semibold tracking-[-.04em] text-white">{value}</p><p className="mt-2 text-[10px] text-slate-400">{detail}</p></div>)}</div>
      <div className="console-card relative min-h-[300px] overflow-hidden p-6 md:col-span-7">
        <div className="flex items-center justify-between"><div><p className="console-label">Global movement trail</p><h3 className="mt-2 text-base font-semibold text-white">Primary Hub · Secure transfer corridor</h3></div><span className="rounded-full border border-cyan/20 bg-cyan/10 px-2.5 py-1 text-[9px] font-bold text-cyan">LIVE</span></div>
        <div className="preview-map absolute inset-x-0 bottom-0 top-20"><svg className="absolute inset-0 h-full w-full" viewBox="0 0 600 260" fill="none" aria-hidden="true"><path d="M-20 220C80 190 97 86 196 112c86 23 111-58 190-37 66 18 103 105 230 29" stroke="rgba(110,216,224,.22)" strokeWidth="30"/><path d="M-20 220C80 190 97 86 196 112c86 23 111-58 190-37 66 18 103 105 230 29" stroke="#6ED8E0" strokeWidth="2" strokeDasharray="7 8"/>{[[74,181],[196,112],[386,75],[522,112]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="9" fill="#0b2134" stroke="#6ED8E0"/><circle cx={x} cy={y} r="3" fill="#6ED8E0"/></g>)}</svg><div className="absolute bottom-5 left-5 right-5 flex justify-between rounded-2xl border border-white/[.08] bg-[#071522]/80 p-3 backdrop-blur-xl">{["Bag drop","Screening","Transfer","Gate"].map((x,i)=><div key={x} className="text-center"><p className="text-[8px] text-slate-500">0{i+1}</p><p className="mt-1 text-[9px] font-semibold text-slate-200">{x}</p></div>)}</div></div>
      </div>
      <div className="grid gap-4 md:col-span-5">
        <div className="console-card p-5"><div className="flex items-center justify-between"><p className="console-label">Identity confidence</p><Fingerprint size={16} className="text-cyan"/></div><p className="mt-6 text-4xl font-semibold text-white">98.7%</p><p className="mt-2 text-[10px] text-slate-400">Passenger, bag, seal, route, and custody signals reconciled.</p></div>
        <div className="console-card p-5"><div className="flex items-center justify-between"><p className="console-label">Standards review posture</p><FileCheck2 size={16} className="text-gold"/></div><p className="mt-6 text-xl font-semibold text-white">Review package prepared</p><p className="mt-2 text-[10px] text-slate-400">Security, facilitation, governance, and pilot evidence mapping.</p></div>
      </div>
    </div>
  </motion.div>;
}

export default function LandingPage() {
  const [menuOpen,setMenuOpen] = useState(false);
  return <main className="min-h-screen overflow-hidden bg-[#f5f5f7] text-[#101114]">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-black/[.06] bg-white/75 backdrop-blur-2xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 md:px-8"><div className="landing-logo"><Logo/></div><div className="hidden items-center gap-9 text-[13px] font-medium text-slate-700 md:flex"><a href="#platform" className="transition hover:text-black">Platform</a><a href="#standards" className="transition hover:text-black">ICAO alignment</a><Link href="/pilot" className="transition hover:text-black">Global pilot</Link><Link href="/about" className="transition hover:text-black">Developer</Link></div><div className="flex items-center gap-2"><Link href="/dashboard" className="premium-button hidden sm:inline-flex">Explore Command Center <ArrowRight size={14}/></Link><button className="grid h-10 w-10 place-items-center rounded-full text-slate-800 md:hidden" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen?<X/>:<Menu/>}</button></div></div>{menuOpen&&<div className="border-t border-black/[.06] bg-white px-5 py-5 md:hidden"><div className="flex flex-col gap-4 text-sm font-medium"><a href="#platform" onClick={()=>setMenuOpen(false)}>Platform</a><a href="#standards" onClick={()=>setMenuOpen(false)}>ICAO alignment</a><Link href="/pilot">Global pilot</Link><Link href="/dashboard" className="premium-button justify-center">Explore Command Center</Link></div></div>}</nav>

    <section className="hero-light relative overflow-hidden bg-[#06101d] px-5 pb-24 pt-36 text-white md:px-8 md:pb-36 md:pt-48"><div className="absolute inset-0 z-0 opacity-80 [mask-image:linear-gradient(to_bottom,black_0%,black_58%,transparent_100%)]"><ThreeScene/></div><div className="absolute inset-0 z-[1] bg-[radial-gradient(circle_at_50%_8%,rgba(110,216,224,.22),transparent_36%),linear-gradient(180deg,rgba(6,16,29,.34),rgba(245,245,247,.92)_88%)]" aria-hidden="true"/><div className="relative z-10 mx-auto max-w-7xl"><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.75}} className="mx-auto max-w-5xl text-center"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-gold/30 bg-[#071522]/75 px-4 py-2 text-[11px] font-semibold text-gold shadow-[0_0_30px_rgba(212,175,55,.14)] backdrop-blur"><ShieldCheck size={13}/> ICAO-aligned review pathway</div><h1 className="text-balance text-6xl font-semibold leading-[.94] tracking-[-.065em] text-white drop-shadow-[0_0_34px_rgba(110,216,224,.28)] sm:text-7xl md:text-[104px]">BAG-DNA OS<span className="align-top text-[.28em] tracking-normal">™</span></h1><h2 className="mx-auto mt-7 max-w-4xl text-balance text-3xl font-semibold leading-[1.08] tracking-[-.045em] text-slate-100 sm:text-4xl md:text-6xl">The global digital identity layer for every checked bag.</h2><p className="mx-auto mt-8 max-w-3xl text-balance text-base leading-7 text-slate-300 md:text-xl md:leading-8">Issue, bind, verify, track, and protect persistent baggage identity across airports, airlines, authorities, and international corridors.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/pilot" className="premium-button justify-center px-6 py-3.5 text-sm">Open Standards Review <ArrowRight size={16}/></Link><Link href="/scanner" className="secondary-button justify-center px-6 py-3.5 text-sm">Run Checkpoint Scan <ChevronRight size={16}/></Link></div></motion.div><div className="mt-20 md:mt-28"><ProductPreview/></div></div></section>

    <section id="platform" className="bg-white px-5 py-28 md:px-8 md:py-40"><div className="mx-auto max-w-7xl"><motion.div {...reveal} className="mx-auto max-w-4xl text-center"><p className="section-kicker">One trusted identity graph</p><h2 className="section-title">Know the bag. Understand the journey.</h2><p className="section-copy mx-auto">BAG-DNA OS is a digital baggage identity issuance, verification, tracking, and chain-of-custody operating system built for globally interoperable aviation workflows.</p></motion.div><div className="mt-16 grid gap-5 md:grid-cols-2">{capabilities.map(({icon:Icon,title,text,href},index)=><motion.article {...reveal} transition={{duration:.6,delay:index*.06}} key={title} className="feature-card group"><span className="feature-icon"><Icon size={22}/></span><p className="mt-12 text-xs font-semibold text-slate-500">0{index+1}</p><h3 className="mt-3 text-2xl font-semibold tracking-[-.03em] md:text-3xl">{title}</h3><p className="mt-4 max-w-lg text-base leading-7 text-slate-600">{text}</p><Link href={href} className="mt-10 inline-flex items-center gap-2 text-sm font-semibold text-[#805d14]">Explore capability <ArrowRight size={15}/></Link></motion.article>)}</div></div></section>

    <section id="standards" className="command-section px-5 py-28 text-white md:px-8 md:py-40"><div className="mx-auto max-w-7xl"><motion.div {...reveal} className="grid gap-8 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><p className="section-kicker text-cyan">International standards posture</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold leading-[1.05] tracking-[-.045em] sm:text-5xl md:text-7xl">Prepared for ICAO-aligned stakeholder evaluation.</h2></div><p className="max-w-xl text-base leading-7 text-slate-300 lg:justify-self-end">The platform translates security, facilitation, interoperability, governance, and pilot outcomes into a review-ready evidence package.</p></motion.div><div className="mt-16 grid gap-4 md:grid-cols-3">{alignment.map((item,index)=><motion.article {...reveal} transition={{duration:.55,delay:index*.08}} key={item.title} className="dark-feature-card"><div className="flex items-center justify-between"><ShieldCheck className="text-cyan"/><b className="text-2xl text-gold">{item.value}</b></div><h3 className="mt-10 text-xl font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{item.text}</p></motion.article>)}</div><p className="mt-8 rounded-2xl border border-gold/20 bg-gold/[.06] p-4 text-xs leading-6 text-slate-300"><b className="text-gold">Transparency note:</b> ICAO alignment describes design intent and standards mapping. BAG-DNA OS does not claim ICAO approval, certification, adoption, or endorsement.</p></div></section>

    <section className="bg-[#f5f5f7] px-5 py-28 md:px-8 md:py-40"><motion.div {...reveal} className="mx-auto grid max-w-7xl overflow-hidden rounded-[32px] bg-white shadow-[0_25px_80px_rgba(15,23,42,.08)] lg:grid-cols-2"><div className="p-8 sm:p-12 md:p-16"><p className="section-kicker">Built for international-scale trust</p><h2 className="mt-5 text-4xl font-semibold leading-[1.08] tracking-[-.045em] md:text-6xl">A controlled global pilot creates defensible proof.</h2><p className="mt-7 max-w-xl text-base leading-7 text-slate-600">A focused multi-airport deployment can demonstrate passenger protection, authority coordination, baggage integrity, and cross-border interoperability.</p><div className="mt-9 space-y-4">{["Corridor-level risk intelligence","Airport, airline, and authority visibility","ICAO-aligned evidence mapping"].map(x=><p key={x} className="flex items-center gap-3 text-sm font-semibold"><span className="grid h-6 w-6 place-items-center rounded-full bg-emerald-50 text-emerald-700"><Check size={13}/></span>{x}</p>)}</div><Link href="/pilot" className="premium-button mt-10">View global pilot strategy <ArrowRight size={15}/></Link></div><div className="pilot-visual relative min-h-[460px] overflow-hidden p-8 sm:p-12"><div className="absolute inset-0 opacity-70"><div className="pilot-orbit"/><div className="pilot-orbit pilot-orbit-2"/></div><div className="relative flex h-full flex-col justify-between"><div className="self-end rounded-2xl border border-white/10 bg-white/[.08] p-4 backdrop-blur-xl"><p className="text-[10px] uppercase tracking-widest text-slate-400">Standards readiness</p><p className="mt-2 text-2xl font-semibold text-white">Phase 01 · Prepared</p></div><div className="rounded-3xl border border-white/10 bg-[#071522]/80 p-6 text-white backdrop-blur-xl"><Globe2 className="text-cyan"/><p className="mt-8 text-xs uppercase tracking-widest text-slate-400">Demonstration corridor</p><p className="mt-2 text-2xl font-semibold">Primary Hub ↔ Global Gateways</p><div className="mt-6 grid grid-cols-3 gap-3 text-center">{[["6","Airlines"],["90 days","Validation"],["4","Authorities"]].map(([a,b])=><div key={b} className="rounded-xl bg-white/[.05] p-3"><b>{a}</b><p className="mt-1 text-[9px] text-slate-400">{b}</p></div>)}</div></div></div></div></motion.div></section>

    <section className="bg-white px-5 py-28 text-center md:px-8 md:py-40"><motion.div {...reveal} className="mx-auto max-w-4xl"><p className="section-kicker">Operational confidence, engineered</p><h2 className="section-title">Every passenger has an identity. Every bag should too.</h2><p className="section-copy mx-auto">Give the global baggage network a secure, intelligent foundation built for international aviation review.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/dashboard" className="premium-button justify-center px-6 py-3.5">Explore Command Center <ArrowRight size={15}/></Link><Link href="/pilot" className="secondary-button justify-center px-6 py-3.5">Review ICAO Alignment</Link></div></motion.div></section>

    <footer className="border-t border-black/[.06] bg-white px-5 py-10 md:px-8"><div className="landing-logo mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 lg:flex-row lg:items-center"><Logo/><nav aria-label="Footer" className="flex flex-wrap gap-x-5 gap-y-3 text-xs font-medium text-slate-600"><Link href="/beta">Assurance</Link><Link href="/integrations">API roadmap</Link><Link href="/investors">Investors</Link><Link href="/pilot">ICAO alignment</Link><Link href="/about">Developer</Link></nav><p className="text-xs text-slate-500">Developed by Paul Iyogun.</p></div></footer>
  </main>;
}
