import { ArrowUpRight, Bot, Braces, Building2, Database, Fingerprint, Github, Globe2, Linkedin, Map, Rocket, ShieldCheck } from "lucide-react";
const layers=[[Globe2,"Aviation context","Free public flight, weather, and map context"],[Fingerprint,"Bag identity","Persistent demonstration identity and journey memory"],[ShieldCheck,"Custody ledger","Hash-linked, append-only evidence design"],[Bot,"Intelligence","Deterministic, explainable incident reasoning"],[Map,"Digital twin","Geospatial corridor and airport-zone reconstruction"],[Database,"Evidence","Reviewable event references and decisions"]] as const;
export function InnovationCenter(){return <div className="innovation-center"><header><div><span>PROJECT PHOENIX · INNOVATION CENTER</span><h1>Building the intelligence layer for every bag journey.</h1><p>A developer-led exploration of GIS, AI, automation, and aviation technology—designed as a credible demonstration, not a claim of deployed integration.</p></div><Rocket/></header>
 <section className="developer-section"><div className="developer-monogram">PI</div><div><small>DEVELOPER</small><h2>Paul Iyogun</h2><p>Developing BAG-DNA OS through <b>ETL GIS Consulting LLC</b>, with a focus on spatial intelligence, explainable automation, aviation operations, and trustworthy evidence systems.</p><span>GIS</span><span>AI</span><span>Automation</span><span>Aviation technology</span></div><nav><a href="https://github.com/Omoluabi1003" target="_blank" rel="noreferrer"><Github/> GitHub <ArrowUpRight/></a><a href="https://www.linkedin.com/in/paul-iyogun-7591a571" target="_blank" rel="noreferrer"><Linkedin/> LinkedIn <ArrowUpRight/></a><a href="https://etl-gis-consulting-llc.vercel.app" target="_blank" rel="noreferrer"><Building2/> ETL GIS Consulting <ArrowUpRight/></a></nav></section>
 <section className="why-section"><small>WHY BAG-DNA</small><h2>Baggage operations generate events. Operators need memory.</h2><div><p>Fragmented scans can describe isolated moments without explaining custody continuity. BAG-DNA explores a persistent bag identity that connects operational context, evidence, and recovery action.</p><p>The vision is global in relevance and intentionally grounded: this release uses controlled baggage demonstration records and labels them clearly.</p></div></section>
 <section className="architecture-section"><header><div><small>SYSTEM ARCHITECTURE</small><h2>Six connected intelligence layers</h2></div><Braces/></header><div>{layers.map(([Icon,title,text],i)=><article key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="evolution-section"><small>PROJECT EVOLUTION</small><h2>From security controls to Mission Control.</h2><div>{[["01","Security foundation","Tenant-aware authorization, custody hashing, audit posture"],["02","Aviation context","Public geospatial and weather context with failure boundaries"],["03","Incident workflow","Operator-led evidence inspection and recorded decisions"],["04","Project Phoenix","Fullscreen mission environment and BAG-DNA Memory"]].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
 <section className="roadmap-section"><div><small>RESEARCH ROADMAP</small><h2>The runway ahead</h2><p>Forward-looking areas for evaluation—not announced enterprise integrations or deployment commitments.</p></div><ol>{["Airport digital twin","BAG-DNA Protocol","Enterprise integration research","SDK","Developer sandbox"].map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></section>
 </div>}
