"use client";
import { useState } from "react";
import { AlertOctagon, ArrowRight, FlaskConical, ShieldAlert } from "lucide-react";
import { AppShell } from "@/components/shell";
const scenarios=[
["Stolen tag on another bag","Bound navy soft-shell bag","Black hard-shell profile","Physical fingerprint and weight cannot reconcile","Quarantine bag; verify passenger and CCTV","Visual scan, scale record, credential graph"],
["Paper tag photographed and reused","Fresh rotating QR window","Expired static QR payload","Cryptographic validation window elapsed","Deny movement; inspect presenter","QR nonce, device, time and zone"],
["RFID does not match QR","RFID and QR resolve to one identity","Two different BAG-DNA identities","Credential graph split","Stop conveyor and isolate both bags","RFID UID, QR payload, scanner event"],
["NFC token mismatch","NFC bound to encrypted token","Unknown NFC UID presented","Secure element binding failed","Escalate to security review","NFC signature and token digest"],
["Weight changed beyond tolerance","18.4 kg ± 1.5 kg","23.1 kg at screening","4.7 kg unexplained increase","Hold for authorized inspection","Issuance and checkpoint weights"],
["Visual fingerprint mismatch","Navy soft shell, green sticker","Silver hard shell, no sticker","Appearance changed across key features","Treat as suspected tag substitution","Original/current imagery and match map"],
["Unauthorized zone entry","Sorting Hub → Loading Bay","Restricted Hold E-7","Route graph does not permit zone","Lock custody and review staff access","Geofence, timestamp, route plan"],
["Tamper seal broken","Seal intact unless inspection authorized","Broken with no authorization","No approved inspection event exists","Quarantine and notify passenger","Seal sensor, NFC, custody history"],
["Route inconsistency","LOS → LHR on BA 074","DXB transfer scan","Checkpoint is outside itinerary","Prevent load and reconcile routing","Flight, location and scan record"],
["Handler outside assignment","Ramp handler assigned Bay C4","Scan performed in Hold E-7","Actor geofence violates assignment","Suspend transfer; supervisor review","Staff ID, assignment, badge location"],
];
export default function MismatchLab(){const [active,setActive]=useState(0);const s=scenarios[active];return <AppShell title="Identity Mismatch Lab" eyebrow="Security testing · Criminal manipulation scenarios"><div className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><section className="glass p-4"><div className="mb-3 flex items-center gap-2 px-2 py-2 text-xs font-bold"><FlaskConical className="text-cyan"/> Attack simulations</div>{scenarios.map((x,i)=><button onClick={()=>setActive(i)} key={x[0]} className={`mb-1 flex w-full items-center justify-between rounded-xl px-3 py-3 text-left text-[11px] ${i===active?"bg-red-400/10 text-red-200":"text-mist hover:bg-white/5"}`}><span>{x[0]}</span><ArrowRight size={13}/></button>)}</section><section className="glass overflow-hidden"><div className="border-b border-red-400/20 bg-red-400/[.06] p-6"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-red-400/10 text-red-300"><AlertOctagon/></span><div><p className="text-[10px] font-bold uppercase tracking-widest text-red-300">Simulation {String(active+1).padStart(2,"0")}</p><h2 className="mt-1 text-2xl font-semibold">{s[0]}</h2></div></div></div><div className="grid gap-3 p-6 sm:grid-cols-2">{[["Expected",s[1]],["Detected",s[2]],["Why it failed",s[3]],["Recommended action",s[4]]].map(([a,b],i)=><div key={a} className={`rounded-2xl border p-5 ${i===1||i===2?"border-red-400/20 bg-red-400/[.04]":"border-white/[.08] bg-white/[.025]"}`}><p className="text-[9px] font-bold uppercase tracking-widest text-mist">{a}</p><p className="mt-3 text-sm font-semibold leading-6">{b}</p></div>)}</div><div className="mx-6 mb-6 rounded-2xl border border-cyan/20 bg-cyan/[.04] p-5"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-cyan"><ShieldAlert size={15}/> Evidence generated</p><p className="mt-3 text-sm">{s[5]}</p><p className="mt-3 font-mono text-[10px] text-mist">ALERT-{String(active+2931)} · event hash preserved · integrity VERIFIED</p></div></section></div></AppShell>}

