"use client";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, CheckCircle2, Fingerprint, KeyRound, Link2, MapPin, SearchCheck, ShieldAlert, UserCheck } from "lucide-react";
import { useState } from "react";
import { phoenixBag } from "@/lib/demo/mission";

const questions=["Where has this bag been?","Who handled it?","Where did custody break?","Which event cannot be trusted?","What should the operator do next?"];
export function BagMemoryExperience(){const [question,setQuestion]=useState(questions[0]);return <div className="memory-experience">
 <header className="memory-header"><div><span><Fingerprint/> BAG-DNA MEMORY</span><h1>{phoenixBag.id}</h1><p>Explainable narrative reconstruction · <b>DEMO DATA</b></p></div><Link href="/dashboard"><ArrowLeft/> Return to Mission Control</Link></header>
 <div className="memory-question"><SearchCheck/><div><small>ASK THE BAG MEMORY</small><b>{question}</b></div><select aria-label="Bag Memory question" value={question} onChange={e=>setQuestion(e.target.value)}>{questions.map(q=><option key={q}>{q}</option>)}</select></div>
 <section className="memory-narrative"><aside><p>IDENTITY</p><div className="identity-orbit"><Fingerprint/><span>99.2%</span></div>{[["STATUS","EXCEPTION"],["FLIGHT",phoenixBag.flight],["ROUTE",phoenixBag.route],["SEAL",phoenixBag.seal],["RISK","87 · HIGH"]].map(([a,b])=><dl key={a}><dt>{a}</dt><dd>{b}</dd></dl>)}</aside><article><span>NARRATIVE RECONSTRUCTION · DEMO DATA</span><h2>Origin custody is credible. Destination custody is not yet explainable.</h2><p>The bag was identified, screened, sorted, and loaded at Miami through four independently supported events. After BDO 2174 arrived in Atlanta, the expected arrival scan did not enter the trusted ledger. Six minutes later, an unregistered device asserted a duplicate custody event in Transfer Zone T4.</p><blockquote>Memory assessment: the bag may be physically present at ATL, but its current holder and seal condition require verification before release.</blockquote></article></section>
 <section className="memory-journey"><header><div><small>JOURNEY</small><h2>Visual custody reconstruction</h2></div><span>4 verified · 1 missing · 1 untrusted</span></header><div>{phoenixBag.events.map((e,i)=><article key={e.id} className={e.evidenceState}><span>{e.evidenceState==="verified"?<CheckCircle2/>:<AlertTriangle/>}</span><small>{e.time} · {e.airport}</small><b>{e.state}</b><p>{e.detail}</p><em>{e.evidenceState}</em>{i<phoenixBag.events.length-1&&<i/>}</article>)}</div></section>
 <div className="memory-grid"><section><span><Link2/> CUSTODY</span><h2>Handoff sequence</h2>{phoenixBag.events.map(e=><p key={e.id}><b>{e.holder}</b><small>{e.zone} · {e.confidence}% confidence</small></p>)}</section><section><span><ShieldAlert/> ANOMALIES</span><h2>Break point</h2><article className="risk-red"><b>+38</b><p>Missing destination scan<small>Expected event absent after arrival window</small></p></article><article className="risk-amber"><b>+24</b><p>Untrusted duplicate<small>Device registration cannot be verified</small></p></article><article><b>+13</b><p>Handler mismatch<small>Event actor outside assigned team</small></p></article></section><section><span><KeyRound/> EVIDENCE</span><h2>Verification state</h2>{[[UserCheck,"Handler","Mismatch"],[KeyRound,"Seal","Inspect"],[Link2,"Hash ledger","Continuity warning"],[MapPin,"Airport zone","ATL T4"]].map(([Icon,a,b])=>{const I=Icon as typeof UserCheck;return <p key={String(a)}><I/><span><b>{String(a)}</b><small>{String(b)}</small></span></p>})}</section></div>
 <section className="recovery-path"><div><span>RECOVERY PATH</span><h2>Restore a trustworthy chain before release.</h2></div><ol>{["Place record on operational hold","Verify destination handler","Inspect seal S-884192","Review device D-991 registration","Escalate if evidence remains unresolved"].map((x,i)=><li key={x}><span>{i+1}</span>{x}</li>)}</ol></section>
 </div>}
