"use client";
import { AlertTriangle, Check, ChevronDown, ClipboardCheck, Cloud, Copy, Crosshair, Database, FileText, Plane, Radio, Search, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { phoenixBag, phoenixFlights } from "@/lib/demo/mission";
import { evidenceSummary, explainMission } from "@/lib/intelligence/missionBriefing";
import { MissionCanvas } from "./MissionCanvas";
import { MissionBriefingPanel } from "./MissionBriefingPanel";
import { JourneyTimeline } from "./JourneyTimeline";
import { airportRegistry, defaultOperationalCorridor, operationalCorridors, resolveCorridorAirports, searchCorridors } from "@/lib/operations/corridors";

export function PhoenixMissionControl(){
 const [corridorId,setCorridorId]=useState(defaultOperationalCorridor.id); const [corridorSearch,setCorridorSearch]=useState(""); const [corridorFilter,setCorridorFilter]=useState<"all"|"domestic"|"international">("all"); const [flight,setFlight]=useState(0); const [index,setIndex]=useState(4); const [playing,setPlaying]=useState(false); const [speed,setSpeed]=useState(1); const [drawer,setDrawer]=useState<"evidence"|"decision"|null>(null); const [decision,setDecision]=useState(""); const [copied,setCopied]=useState(false);
 const selectedCorridor=operationalCorridors.find(item=>item.id===corridorId)??defaultOperationalCorridor; const hasCaseData=selectedCorridor.scenario?.hasCompleteCaseData===true; const corridorAirports=resolveCorridorAirports(selectedCorridor); const filteredCorridors=searchCorridors(corridorSearch,corridorFilter); const corridorRegions=[...new Set(filteredCorridors.map(item=>item.region))];
 const briefing=useMemo(()=>explainMission(phoenixBag.events,phoenixBag.briefing),[]); const event=phoenixBag.events[index];
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setIndex(i=>{if(i>=phoenixBag.events.length-1){setPlaying(false);return i}return i+1}),1200/speed);return()=>clearInterval(timer)},[playing,speed]);
 async function generate(){await navigator.clipboard?.writeText(evidenceSummary(briefing));setCopied(true);setTimeout(()=>setCopied(false),1800)}
 return <div className="mission-control">
  <aside className="mission-left"><div className="case-state"><span><Radio/> {hasCaseData?"ACTIVE INCIDENT":"CORRIDOR PREVIEW"}</span><b>{selectedCorridor.scenario?.caseId??selectedCorridor.id.toUpperCase()}</b><small>{selectedCorridor.scenario?.label??"No case evidence attached"}</small><em>DEMO CONTEXT</em></div>
   <label className="ops-select"><span>AIRPORT CORRIDOR</span><input aria-label="Search corridors by airport, city, or country" value={corridorSearch} onChange={e=>setCorridorSearch(e.target.value)} placeholder="Search code, city, country"/><select aria-label="Filter corridors" value={corridorFilter} onChange={e=>setCorridorFilter(e.target.value as typeof corridorFilter)}><option value="all">All corridors</option><option value="domestic">Domestic</option><option value="international">International</option></select><select aria-label="Select airport corridor" value={corridorId} onChange={e=>{setCorridorId(e.target.value);setIndex(e.target.value===defaultOperationalCorridor.id?4:0);setPlaying(false);setDrawer(null)}}>{corridorRegions.map(region=><optgroup key={region} label={region}>{filteredCorridors.filter(item=>item.region===region).map(item=>{const origin=airportRegistry[item.originAirportCode];const destination=airportRegistry[item.destinationAirportCode];return <option key={item.id} value={item.id}>{item.displayName} · {origin.city} to {destination.city}</option>})}</optgroup>)}</select><ChevronDown/></label>
   <div className="flight-list"><p>{hasCaseData?"SELECTED FLIGHT":"SELECTED CORRIDOR"} <span>01</span></p>{hasCaseData?phoenixFlights.slice(0,1).map((f,i)=><button key={f.number} className={flight===i?"active":""} onClick={()=>{setFlight(i);setIndex(4)}}><span><Plane/><b>{f.number}</b><em className={f.risk.toLowerCase()}>{f.risk}</em></span><strong>{selectedCorridor.displayName}</strong><small>{f.status} · {f.bags} bags</small></button>):<button className="active"><span><Plane/><b>PREVIEW ONLY</b><em>NOMINAL DEMO</em></span><strong>{selectedCorridor.displayName}</strong><small>{corridorAirports.origin.city} to {corridorAirports.destination.city} · {selectedCorridor.estimatedDurationMinutes} min</small></button>}</div>
   <div className="alert-stack"><p>{hasCaseData?"ACTIVE ALERTS":"CORRIDOR ALERTS"} <span>{hasCaseData?"02":"00"}</span></p>{hasCaseData?<><button onClick={()=>{setFlight(0);setIndex(4)}}><AlertTriangle/><span><b>Missing arrival scan</b><small>{phoenixBag.id}</small></span><em>HIGH</em></button><button onClick={()=>{setFlight(0);setIndex(5)}}><Database/><span><b>Untrusted duplicate</b><small>Device D-991</small></span><em>REVIEW</em></button></>:<p className="px-2 py-3 text-[8px] leading-4 text-mist">No alerts or evidence are attached to this preview.</p>}</div>
   <div className="public-feeds"><p>PUBLIC CONTEXT</p><span><i/><Cloud/> NOAA METAR <small>Cached · 19:38</small></span><span><i/><Plane/> OpenSky <small>Context ready</small></span><span><i/><Crosshair/> OpenStreetMap <small>Map context</small></span></div>
  </aside>
  <div className="mission-center"><div className="mission-strip"><div><small>{hasCaseData?"SELECTED BAG · DEMO DATA":"OPERATIONAL CORRIDOR · PREVIEW"}</small><b>{hasCaseData?phoenixBag.id:selectedCorridor.displayName}</b></div><span><small>CONTEXT</small><b>{hasCaseData?phoenixFlights[flight].number:selectedCorridor.category.toUpperCase()}</b></span><span><small>STATUS</small><b className={hasCaseData?"warn":""}>{hasCaseData?"EXCEPTION":"NO CASE DATA"}</b></span><span><small>REGION</small><b>{selectedCorridor.region}</b></span>{hasCaseData&&<button onClick={()=>setDrawer("evidence")}><Search/> Inspect evidence</button>}</div>
   <MissionCanvas event={event} index={index} total={phoenixBag.events.length} corridor={selectedCorridor} hasCaseData={hasCaseData}/>
  </div>
  {hasCaseData?<MissionBriefingPanel briefing={briefing} onEvidence={()=>setDrawer("evidence")}/>:<aside className="briefing-panel"><header><span><ShieldCheck/> CORRIDOR PREVIEW</span><b>DEMO CONTEXT</b></header><section className="brief-situation"><small>SELECTED CORRIDOR</small><p>{corridorAirports.origin.iataCode} · {corridorAirports.origin.city}, {corridorAirports.origin.country} to {corridorAirports.destination.iataCode} · {corridorAirports.destination.city}, {corridorAirports.destination.country}</p></section><section><h3>DATA BOUNDARY</h3><p className="mt-2 text-[10px] leading-5 text-mist">This selection demonstrates route geometry and operational framing only. No baggage, custody, alert, risk, or investigation evidence is asserted for this corridor.</p></section></aside>}
  {hasCaseData?<JourneyTimeline events={phoenixBag.events} index={index} playing={playing} speed={speed} onIndex={setIndex} onPlaying={setPlaying} onSpeed={setSpeed}/>:<section className="journey-timeline grid place-items-center text-[10px] tracking-wider text-mist">CORRIDOR PREVIEW · JOURNEY REPLAY UNAVAILABLE WITHOUT CASE DATA</section>}
  <div className="decision-bar"><span><ShieldCheck/> {hasCaseData?"OPERATOR WORKFLOW":"CORRIDOR PREVIEW · NO EVIDENCE WORKFLOW"}</span>{hasCaseData&&<><button onClick={()=>setDrawer("decision")}><ClipboardCheck/> Record operational decision</button><button onClick={generate}><FileText/> {copied?"Evidence summary copied":"Generate demo evidence summary"}</button></>}</div>
  {drawer&&<div className="ops-drawer-backdrop" onClick={()=>setDrawer(null)}><aside className="ops-drawer" onClick={e=>e.stopPropagation()}><header><div><small>{drawer==="evidence"?"CUSTODY EVIDENCE":"OPERATOR DECISION"}</small><h2>{drawer==="evidence"?"Evidence inspector":"Record response"}</h2></div><button onClick={()=>setDrawer(null)}>Close</button></header>{drawer==="evidence"?<><p className="demo-notice">DEMO DATA · Evidence generated for scenario BDO-DEMO-001</p>{briefing.evidence.map(e=><article key={e.id} className={e.state}><span>{e.id}</span><div><b>{e.label}</b><p>{e.detail}</p></div><em>{e.state}</em></article>)}<button className="drawer-primary" onClick={generate}><Copy/> {copied?"Copied to clipboard":"Copy evidence summary"}</button></>:<><p>Select a controlled demonstration response. Recording is local to this browser session.</p>{["Place bag record on operational hold","Verify destination handler","Inspect seal status","Escalate to baggage security"].map(a=><button className={`decision-option ${decision===a?"selected":""}`} key={a} onClick={()=>setDecision(a)}><span>{decision===a?<Check/>:null}</span>{a}</button>)}<textarea aria-label="Decision note" placeholder="Add operator rationale…"/><button className="drawer-primary" disabled={!decision} onClick={()=>setDrawer(null)}><ClipboardCheck/> Record demo decision</button></>}</aside></div>}
 </div>
}
