import { CheckCircle2, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/shell";
import { BagDnaProcessFlow } from "@/components/process/BagDnaProcessFlow";
import { primaryDemoBag } from "@/lib/data/demoWorkflow";
import { verifyBag } from "@/lib/verification/verificationEngine";
import { buildTrustGraph, detectThreatPatterns, calculateIdentityConfidence, calculateIntegrityScore } from "@/lib/intelligence";

export default function VerificationCenter() {
  const last = primaryDemoBag.custodyEvents.at(-1)!;
  const result = verifyBag(primaryDemoBag,{rfidUid:primaryDemoBag.rfid.uid,nfcUid:primaryDemoBag.nfc.uid,qrPayload:primaryDemoBag.qr.payload,weightKg:primaryDemoBag.physicalProfile.weightKg,sealStatus:primaryDemoBag.seal.status,actualCheckpoint:last.checkpoint,expectedCheckpoint:last.checkpoint,staffAssignedZone:last.actor.assignedZone,staffActualZone:last.actor.actualZone,visualProfile:primaryDemoBag.physicalProfile});
  const trust = buildTrustGraph(); const threat = detectThreatPatterns(); const identity = calculateIdentityConfidence(); const integrity = calculateIntegrityScore();
  return <AppShell title="Verification Center" eyebrow="Primary same-bag proof engine"><BagDnaProcessFlow/><section className="mt-6 grid gap-3 md:grid-cols-4">{[["Trust Graph impact", trust.explanation],["Threat Graph impact", threat.evidence[0]],["Identity Confidence explanation", identity.verificationSummary],["Integrity Score explanation", integrity.explanation]].map(([a,b])=><div key={a} className="glass p-4"><p className="text-[10px] uppercase tracking-widest text-gold">{a}</p><p className="mt-2 text-xs leading-5 text-mist">{b}</p></div>)}</section><div className="mt-6 grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><section className="glass p-6"><label className="text-[10px] font-bold uppercase tracking-widest text-slate-300">BAG-DNA ID input<input defaultValue={primaryDemoBag.bagDnaId} className="mt-3 w-full rounded-xl border border-white/10 bg-[#0b2134] p-4 font-mono text-cyan"/></label><button className="mt-4 w-full rounded-xl bg-cyan p-3.5 text-xs font-black text-ink">Run complete verification</button><div className="mt-6 rounded-2xl border border-emerald-400/25 bg-emerald-400/[.08] p-5"><CheckCircle2 className="text-emerald-300"/><p className="mt-4 text-[10px] uppercase tracking-widest text-emerald-300">Verification result</p><h2 className="mt-1 text-3xl font-semibold uppercase">{result.decision}</h2><p className="mt-2 text-xs leading-5 text-slate-300">{result.reasons[0]}</p></div></section><section className="glass p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-widest text-gold">Bag Integrity Score</p><h2 className="mt-2 text-5xl font-semibold">{result.score}<span className="text-lg text-slate-400"> / 100</span></h2><p className="mt-2 text-sm text-emerald-300">{result.integrity.band}</p></div><ShieldCheck size={42} className="text-cyan"/></div><div className="mt-6 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(result.checks).map(([name,pass])=><div key={name} className="rounded-xl border border-white/[.08] bg-white/[.03] p-3"><p className="text-[9px] capitalize text-slate-300">{name.replace(/([A-Z])/g," $1")}</p><b className={pass?"mt-2 block text-xs text-emerald-300":"mt-2 block text-xs text-red-300"}>{pass?"VERIFIED":"FAIL"}</b></div>)}</div><div className="mt-5 rounded-2xl border border-cyan/20 bg-cyan/[.05] p-5"><p className="text-[10px] uppercase tracking-widest text-cyan">Recommended action</p><p className="mt-2 text-sm leading-6">{result.recommendedAction}</p></div></section></div></AppShell>;
}
