import { Check, Clock3, Plane, ShieldCheck } from "lucide-react";
const stages=[
 ["Bag accepted","Lagos check-in identity and weight matched","14:08"],
 ["Security cleared","Screening complete with seal integrity confirmed","14:22"],
 ["Custody transfer verified","Authorized handler handoff recorded","14:41"],
 ["Loaded on aircraft","Baggage reconciled to flight BA 074","15:03"],
 ["Arrival processing","Next verification after aircraft arrival","Pending"],
 ["Claim release","Passenger identity check required at collection","Pending"]
];
export function PassengerTracker(){return <div><div className="mb-7 flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-widest text-slate-600">BA 074 · Lagos → London</p><h2 className="mt-2 text-2xl font-semibold text-slate-950">Your bag is securely on board</h2><p className="mt-2 text-sm leading-6 text-slate-600">BAG-DNA ID BD-7A92-1184 is reconciled to Omoluabi Paul.</p></div><div className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-emerald-100 text-emerald-800"><Plane size={22}/></div></div><div className="relative space-y-2">{stages.map(([title,detail,time],i)=><div key={title} className={`grid grid-cols-[32px_1fr] gap-3 rounded-xl border p-3.5 ${i===3?"border-cyan-300 bg-cyan-50":"border-slate-200 bg-white"}`}><span className={`grid h-8 w-8 place-items-center rounded-full ${i<4?"bg-emerald-700 text-white":"border border-slate-300 bg-slate-50 text-slate-600"}`}>{i<4?<Check size={15}/>:<Clock3 size={14}/>}</span><div><div className="flex flex-wrap justify-between gap-2"><b className="text-sm text-slate-950">{title}</b><span className="text-xs font-semibold text-slate-600">{time}</span></div><p className="mt-1 text-xs leading-5 text-slate-600">{detail}</p>{i===3&&<span className="mt-2 inline-block rounded-full bg-cyan-900 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-white">Current stage</span>}</div></div>)}</div><div className="mt-6 flex gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><ShieldCheck className="shrink-0 text-emerald-800" size={20}/><div><b className="text-sm text-emerald-950">Tamper seal verified</b><p className="mt-1 text-xs leading-5 text-emerald-900">No unauthorized opening event detected. Last custody verification: Lagos loading bay, 4 minutes ago.</p></div></div></div>}
